[features]
seeds = false
skip-lint = false

[programs.localnet]
token_distribution = "Gnkd6cywkkrSS4Hq9eSr3vf8EeovLzXYcZMoN6zKJY5J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
